stages :
   - maven_build
   - deploy_dev

Job1:
  stage: maven_build
  script: 
     - mvn kbuilder:all
     - mvn clean install
  artifacts:
    paths:
      - target/
  only:
    - master
Job2:
  stage: deploy_dev
  script:
    - scp -o stricthostkeychecking=no target/*.jar karaz@151.80.213.52:/home/karaz
    - ssh -o stricthostkeychecking=no karaz@151.80.213.52 "unzip -o karaz-ux-hub-1.0.jar -d karaz-ux-hub-1.0/ && rm -rf /home/karaz/payara5/glassfish/domains/domain1/autodeploy/karazApp/karaz-ux-hub-1.0 && mv karaz-ux-hub-1.0 /home/karaz/payara5/glassfish/domains/domain1/autodeploy/karazApp/ "
    - ssh -o stricthostkeychecking=no karaz@151.80.213.52 "./restart_payara.sh"
  only:
    - master