stages :
   - maven_build
   - deploy_dev

Job1:
  stage: maven_build
  script: 
     - mvn kbuilder:all
     - mvn clean install
  artifacts:
    paths:
      - target/
  only:
    - Master_CI
Job2:
  stage: deploy_dev
  script:
    - scp -o stricthostkeychecking=no target/*.jar karaz@front-formation.karaz.org:/home/karaz
    - ssh -o stricthostkeychecking=no karaz@front-formation.karaz.org "unzip -o karaz-ux-hub-1.0.jar -d karaz-ux-hub-1.0/ && rm -rf /karaz/payara5/glassfish/domains/domain1/autodeploy/karazApp/karaz-ux-hub-1.0 && mv karaz-ux-hub-1.0 /karaz/payara5/glassfish/domains/domain1/autodeploy/karazApp/ "
    - ssh -o stricthostkeychecking=no karaz@front-formation.karaz.org "/karaz/restart_payara.sh"
  only:
    - Master_CI
