stages :
   - maven_build
   - deploy_dev

Job1:
  stage: maven_build
  script: 
     - mvn kbuilder:all
     - mvn clean install
  artifacts:
    paths:
      - target/
  only:
    - medkh
Job2:
  stage: deploy_dev
  script:
    - scp -o stricthostkeychecking=no target/*.jar karaz@51.255.76.236:/home/karaz
    - ssh -o stricthostkeychecking=no karaz@51.255.76.236 "unzip -o karaz-ux-hub-1.0.jar -d karaz-ux-hub-1.0/ && rm -rf /home/karaz/glassfish5/glassfish/domains/domain2/autodeploy/karazApp/karaz-ux-hub-1.0 && mv karaz-ux-hub-1.0 /home/karaz/glassfish5/glassfish/domains/domain2/autodeploy/karazApp"
    - ssh -o stricthostkeychecking=no karaz@51.255.76.236 "/home/karaz/restart_glassfish_domain2.sh"
  only:
    - medkh
