stages :
   - build
   - deploy_dev
Build:
  
  stage: build
  tags : 
    - docker

  script: 
    - mvn kbuilder:all
    - mvn clean install 
    - mvn deploy
     
  artifacts :
    paths:
      - target/
  only:
    - Master_CI 
Job2:
   stage: deploy_dev
   script:
     - scp -o stricthostkeychecking=no target/*.jar karaz@151.80.213.61:/home/karaz
     - ssh -o stricthostkeychecking=no karaz@151.80.213.61 "unzip -o karaz-ux-hub-1.0.jar -d karaz-ux-hub-1.0/ && rm -rf /karaz/glassfish5/glassfish/domains/domain1/autodeploy/karazApp/karaz-ux-hub-1.0 && mv karaz-ux-hub-1.0 /karaz/glassfish5/glassfish/domains/domain1/autodeploy/karazApp/ "
     - ssh -o stricthostkeychecking=no karaz@151.80.213.61 "/karaz/restart_glassfish.sh"
   only:
     - Master_CI
     
